[package]
name = "bibtex-format"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["display", "from"] }
